### ISSUE TITLE
Human entity can't display completely

### ISSUE THREAD

**Issue by Atara6431** [dresnite/npcdialog#10]
All the original entity can display completely,but when you try to use this on npc-human/player entity,it can't work perfectly.
I was really trouble about this question,can you give me some advice?
here's the picture
![596F72078DD413306A98FA24FF8F6FE9](https://user-images.githubusercontent.com/48610466/170618416-29e72807-965e-4b52-a22a-72535bbeeae0.jpg)

**Comment by Skintrphoenix** [comment]
how to open the dialog? i spawn entity like in readme.md and pair entity to dialog

**Comment by thebigsmileXD** [comment]
Quoting the README:
> [...] have the dialog form (**it can't be a player!**). For [...]

You open it by clicking the entity if i remember correctly. But i am currently in the progress of debugging if this is still functional

**Comment by thebigsmileXD** [comment]
@Atara6431 I think what you mean is the skin renderer position? 
That is defined by `portrait_offsets` when sending a skin / adding a player.
Part of AddPlayer packet log:
```php
  EntityMetadata:map[
    uint32
  ]interface{
    
  }{
    0x0:844459289886720,
    0x3:0x0,
    0x4:"┬ºa┬ºlStore",
    0x5:-1,
    0x6:0,
    0x7:300,
    0x8:0,
    0x9:0x0,
    0x25:-1,
    0x26:1,
    0x27:0x1,
    0x28:"{\"picker_offsets\":{\"scale\":[0,0,0],\"translate\":[0,0,0]},\"portrait_offsets\":{\"scale\":[1,1,1],\"translate\":[0,-55,0]}}",
    0x29:"[]",
    0x2a:300,
    0x35:0.6,
    0x36:1.8,
    0x51:0x1,
    0x54:"",
    0x5c:0,
    0x64:""
  },
```

You can set the `EntityMetadataProperty::NPC_SKIN_INDEX` of your entitiy accordingly

**Comment by inxomnyaa** [comment]
This is a configuration issue on the user side of things and unrelated to this virion. Help has still been provided.
